### ISSUE TITLE
Windows 7 platform compatible

### ISSUE THREAD

**Issue by Lis105** [vigri/scantailor-advanced#17]
Please! Compile release ST 1.0.18 for Windows 7.

**Comment by vigri** [comment]
The 1.0.18 release is built with Qt 6. Unfortunately, windows 7 is no longer supported.

However @kunzjacq has done a lot of work to still support Qt 5 **and** Qt 6 when building ST.
Please follow the information given on this page to build ST with Qt 5: https://github.com/vigri/scantailor-libs-build/blob/master/README.md
