### ISSUE TITLE
Feature request: negative margins

### ISSUE THREAD

**Issue by AlexJacobs1977** [vigri/scantailor-advanced#3]
The select content algorithm is not perfect. Please allow for negative margins in "margins". (top/bottom/left/right) Probably an easy fix.

**Comment by vigri** [comment]
Hi Alex,

I've made a quick check of your request. There seems to be no problem for alowing negative margins.

![st](https://user-images.githubusercontent.com/2580723/153097662-cafa1d23-42b0-40f8-8564-547c612e5154.png)
![st2](https://user-images.githubusercontent.com/2580723/153097672-d332ebe4-0509-415d-bf04-dcb00bed665a.png)


However, I do not want to make the decision myself whether it makes sense to allow negative margins or not.
It would be good if someone from the other users could give his/her opinion.

**Comment by AlexJacobs1977** [comment]
I'm unable to enter negative margins. 

I'm also unable to go below zero using the arrows. Once the value hits zero, the arrow becomes grayed out. 

I use windows 7, ST version 1.0.17 64 bit.
![Arrow](https://user-images.githubusercontent.com/63451730/153197705-e390f97f-7a86-40c6-8f88-795102ca0ac6.jpg)

**Comment by vigri** [comment]
I expressed myself in a misleading way, sorry for that :)

As you wrote, the current release does not support negative margins.
The screenshots above a from a quick test I made. I've enabled negative margins in the source code.

But:
> However, I do not want to make the decision myself whether it makes sense to allow negative margins or not.
> It would be good if someone from the other users could give his/her opinion.

**Comment by darnn** [comment]
I'm not entirely sure what the use case for it, but I don't think it can hurt (except maybe with Auto Margins, which I can't comment on since I don't use it). At worst those who don't need it just wouldn't use it.

**Comment by AlexJacobs1977** [comment]
> 

To delete page numbers because scantailor fails to exclude them.

**Comment by AlexJacobs1977** [comment]
> 

Many thanks for considering this.

**Comment by vigri** [comment]
Next week I'll create a pre-release where this feature ist include.

Best regards

**Comment by AlexJacobs1977** [comment]
Thank you! Big thanks!

 
 

Sent: Saturday, March 19, 2022 at 10:07 PM

**Comment by AlexJacobs1977** [comment]
Would to see a release which uses negative margins. :)

**Comment by vigri** [comment]
Finally... https://github.com/vigri/scantailor-advanced/releases/tag/v1.0.18 ;-)
