### ISSUE TITLE
Consider moving this repository to a GitHub organization

### ISSUE THREAD

**Issue by lightsilverberryfox** [vigri/scantailor-advanced#35]
Hi @vigri I suggest moving this fork to an organization, that way, backup admins can be assigned (this would prevent what happened with the original 4lex4 scantailor fork, since another Owner could take over the project), I also believe organizations get better visibility (issue #27)) and on top of that, creating an organization makes the project look more "professional".

**Comment by vigri** [comment]
Hi @lightsilverberryfox 
thanks for your suggestion. Please drop me a mail  to _gh_lightsilverberryfox[at]vigri[dot]de_ (thats a temporary one which I'll delete soon).

**Comment by lightsilverberryfox** [comment]
@vigri Have you received my email?

**Comment by lightsilverberryfox** [comment]
Migrated to organization.

**Comment by trufanov-nok** [comment]
I guess it will be better if you offer 4alex4 an invite to orgenization members. Evenif he doesn't reply.    
And you shall know that being a fork of some other project on github nowadays assume some penalties from github. It won't be on top of the search and afaik one can't search the codebase of the fork. Only issues and docs are searched. So it will be better to discontinue the fork connection between the projects. There is a way to do this. I did the same when MS introduced these penalties and disconnected my fork connection with original ST project.

**Comment by lightsilverberryfox** [comment]
@trufanov-nok That's why we were thinking about making the repository a standard one and not a fork.
