### ISSUE TITLE
Feature request: automatically startup with custom profile

### ISSUE THREAD

**Issue by AlexJacobs1977** [vigri/scantailor-advanced#6]
It's a bit silly; I have my custom settings in a custom profile. But I have to select the custom profile via "default parameters" before doing something.

It would be great if scan tailor advanced would remember which profile to use when starting up. Currently it always starts the default profile, which can not be manipulated.

It happens in the windows version. I'm not sure if the linux version has the same problem.

**Comment by vigri** [comment]
do you use the latest version? https://github.com/vigri/scantailor-advanced/releases/tag/v1.0.17

I've created a custom profile, closed Scan Tailor and opened it again.
The custom profile was loaded automatically.

**Comment by AlexJacobs1977** [comment]
Well darn it, I made a mistake! It works! The error is at my end. I forgot to press the save button. I'm the silly one.
